-- Run in the Supabase dashboard → SQL Editor
-- Creates the table for /festival "I will bear witness" RSVPs

create table public.meygod_festival_rsvps (
  id bigint generated by default as identity primary key,
  name text not null default '',
  email text not null,
  created_at timestamptz not null default now()
);

alter table public.meygod_festival_rsvps enable row level security;

create policy "anon can bear witness"
  on public.meygod_festival_rsvps
  for insert
  to anon
  with check (true);
